name: CI

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  build-and-test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.0'
      - name: Build
        run: xcodebuild -scheme dynamiq -project dynamiq/dynamiq.xcodeproj -configuration Debug build | xcpretty
      - name: Test
        run: xcodebuild test -scheme dynamiq -project dynamiq/dynamiq.xcodeproj -destination 'platform=macOS' | xcpretty
